module.exports = {
    header: `\
    import {
    Account,
    Attr,
    AudioTrack,
    BufferSource,
    ClientRect,
    CSSRule,
    DataTransferItem,
    DOMRect,
    DOMPoint,
    Element,
    File,
    FormDataEntryValue,
    GLboolean,
    GLfloat,
    GLint,
    GLuint,
    GLenum,
    GLsizei,
    IDBIndex,
    IDBIndexParameters,
    IIRFilterNode,
    MimeType,
    MediaKeySystemAccess,
    MediaKeySystemConfiguration,
    MediaKeyStatus,
    Node,
    SourceBuffer,
    SpeechGrammar,
    SpeechRecognitionAlternative,
    StyleSheet,
    SVGLength,
    SVGNumber,
    ScopedCredentialInfo,
    ScopedCredentialParameters,
    ScopedCredentialOptions,
    PeriodicWave,
    PeriodicWaveConstraints,
    RTCRtpCodecCapability,
    RequestInfo,
    TextTrack,
    TextTrackCue,
    Touch,
    VideoTrack,
    VRLayer,
    WebGLUniformLocation,
    WebGLProgram
} from './dom';
import {ReadonlyMap, IterableIterator} from "./es2015.iterable";
`
};
